version: '3.7'
services:
  tbd-database:
    image: postgres
    env_file:
      - database.env
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    dumps: